"""empty message

Revision ID: 820a56d4b62a
Revises: 99755b2a2970
Create Date: 2023-02-02 00:55:03.565139

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '820a56d4b62a'
down_revision = '99755b2a2970'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
