version: '3.8'

services:
  service_1:
    build:
      context: .
      dockerfile: compose/service_1/Dockerfile
    command: /start.sh
    ports:
      - "80:8001"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - internal_backend

  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - ./.env/.rabbitmq.env
    networks:
      - internal_backend

networks:
  internal_backend:
    driver: bridge
