"""empty message

Revision ID: 99755b2a2970
Revises: 
Create Date: 2023-02-02 00:44:46.049735

"""

# revision identifiers, used by Alembic.
revision = "99755b2a2970"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
