#!/bin/bash

set -o errexit
set -o nounset

# --filter python tells watchfiles to only watch py files.
# 'celery -A main.celery worker --loglevel=info' is the command we want watchfiles to run
# By default, watchfiles will watch the current directory and all subdirectories
watchfiles \
  --filter python \
  'celery -A main.celery worker --loglevel=info -Q high_priority,default'

# Here, we added the -Q option to the command to specify the queues enabled (high_priority and default) for the worker.